### ISSUE TITLE
GET：「Hello World」が返らない

### ISSUE THREAD

**Issue by sw-otay** [sw-kanekoi/kanekoi-training-web#1]
>①GET：「Hello World」を返す
>curl -X "GET" "http://localhost:4000/hello"

こちらのコマンドで「Hello World」が返りません。
ご確認をお願いします。

**Comment by sw-kanekoi** [comment]
http://localhost:4000/hello のときはHello Worldをレスポンス
http://localhost:4000 のときは./public/index.htmlをレスポンス
にそれぞれ修正いたしました。

**Comment by sw-otay** [comment]
確認しました！
